<template>
  <div class="list-of-comments">
    <div v-for="comment in comments"
      :key="comment.id"
      :id="comment.id"
      draggable
      @dragstart='startDrag($event, comment)'
      class="comment-li md-elevation-8 hidden"
    >
      <span class="comment md-headline">{{ comment.comment }}</span>
      <span class="authored_by md-caption">{{ comment.authored_by }}</span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Comments',
  methods: {
    startDrag: (ev, comment) => {
      // eslint-disable-next-line
      ev.dataTransfer.dropEffect = 'move';
      // eslint-disable-next-line
      ev.dataTransfer.effectAllowed = 'move';
      ev.dataTransfer.setData('commentID', comment.id);

      const dropzone = document.querySelectorAll('.dropzone');
      for (let i = 0; i < dropzone.length; i += 1) {
        dropzone[i].style.background = 'rgba(123, 123, 123, .2)';
        setTimeout(() => {
          dropzone[i].style.background = 'none';
        }, 2500);
      }
    },
  },
  mounted() {
    const data = {
      dropzone: document.querySelectorAll('.dropzone'),
      comments: document.querySelectorAll('.comment-li'),
    };

    const { dropzone, comments } = data;
    const width = (
      window.innerWidth
      // accessible
      || document.documentElement.clientWidth || document.body.clientWidth
    );

    if (width >= 960) {
      // if big screen make draggable
      for (let i = 0; i < comments.length; i += 1) {
        const randomZone = dropzone[Math.floor(Math.random() * dropzone.length)];
        randomZone.appendChild(comments[i]);
      }
    } else {
      // fill grid spaces. Not draggable
      for (let i = 0; i < comments.length; i += 1) {
        comments[i].draggable = '';
        dropzone[0].appendChild(comments[i]);
      }
    }
  },
  props: {
    comments: {
      type: Array,
    },
  },
};
</script>

<style>
.hidden {
  display: none !important;
}

.comment-li {
  background: rgba(6, 214, 160, .9);
  width: fit-content;
  margin: 2px;
  padding: 12px 24px;
  border-radius: 6px;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  cursor: pointer;
}

.comment-li > span:last-child {
  align-self: flex-end;
}

.fade-in {
  -webkit-animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-3-1 19:18:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

</style>
