<template>
  <div class="list-of-comments">
    <div v-for="comment in comments"
      :key="comment.id"
      :id="comment.id"
      class="comment-li md-elevation-8 hidden"
    >
      <span class="comment md-headline">{{ comment.comment }}</span>
      <span class="authored_by md-caption">{{ comment.authored_by }}</span>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Comments',
  props: {
    comments: {
      type: Array,
    },
  },
};
</script>

<style>
.list-of-comments {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}

.hidden {
  display: none !important;
}

.comment-li {
  background: rgba(6, 214, 160, .9);
  width: fit-content;
  margin: 2px;
  padding: 12px 24px;
  border-radius: 6px;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}

.comment-li > span:last-child {
  align-self: flex-end;
}

.fade-in {
  -webkit-animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-3-1 19:18:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

</style>
